
#DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douka?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#DriverClass
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
#DB username
    username: root
#DB password
    password: root
    
    
    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
  



  