package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RechargeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.record_id
	 * @mbg.generated
	 */
	private String recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.rmb
	 * @mbg.generated
	 */
	private BigDecimal rmb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recharge_record.pay_way
	 * @mbg.generated
	 */
	private Integer payWay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.record_id
	 * @return  the value of recharge_record.record_id
	 * @mbg.generated
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.record_id
	 * @param recordId  the value for recharge_record.record_id
	 * @mbg.generated
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId == null ? null : recordId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.rmb
	 * @return  the value of recharge_record.rmb
	 * @mbg.generated
	 */
	public BigDecimal getRmb() {
		return rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.rmb
	 * @param rmb  the value for recharge_record.rmb
	 * @mbg.generated
	 */
	public void setRmb(BigDecimal rmb) {
		this.rmb = rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.create_time
	 * @return  the value of recharge_record.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.create_time
	 * @param createTime  the value for recharge_record.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.status
	 * @return  the value of recharge_record.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.status
	 * @param status  the value for recharge_record.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.user_id
	 * @return  the value of recharge_record.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.user_id
	 * @param userId  the value for recharge_record.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recharge_record.pay_way
	 * @return  the value of recharge_record.pay_way
	 * @mbg.generated
	 */
	public Integer getPayWay() {
		return payWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recharge_record.pay_way
	 * @param payWay  the value for recharge_record.pay_way
	 * @mbg.generated
	 */
	public void setPayWay(Integer payWay) {
		this.payWay = payWay;
	}
}