package com.example.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class UserRelationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_relation
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_relation
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_relation
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public UserRelationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_relation
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserRelationIdIsNull() {
			addCriterion("user_relation_id is null");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdIsNotNull() {
			addCriterion("user_relation_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdEqualTo(String value) {
			addCriterion("user_relation_id =", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdNotEqualTo(String value) {
			addCriterion("user_relation_id <>", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdGreaterThan(String value) {
			addCriterion("user_relation_id >", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_relation_id >=", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdLessThan(String value) {
			addCriterion("user_relation_id <", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdLessThanOrEqualTo(String value) {
			addCriterion("user_relation_id <=", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdLike(String value) {
			addCriterion("user_relation_id like", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdNotLike(String value) {
			addCriterion("user_relation_id not like", value, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdIn(List<String> values) {
			addCriterion("user_relation_id in", values, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdNotIn(List<String> values) {
			addCriterion("user_relation_id not in", values, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdBetween(String value1, String value2) {
			addCriterion("user_relation_id between", value1, value2, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserRelationIdNotBetween(String value1, String value2) {
			addCriterion("user_relation_id not between", value1, value2, "userRelationId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdIsNull() {
			addCriterion("share_user_id is null");
			return (Criteria) this;
		}

		public Criteria andShareUserIdIsNotNull() {
			addCriterion("share_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andShareUserIdEqualTo(String value) {
			addCriterion("share_user_id =", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdNotEqualTo(String value) {
			addCriterion("share_user_id <>", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdGreaterThan(String value) {
			addCriterion("share_user_id >", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("share_user_id >=", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdLessThan(String value) {
			addCriterion("share_user_id <", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdLessThanOrEqualTo(String value) {
			addCriterion("share_user_id <=", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdLike(String value) {
			addCriterion("share_user_id like", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdNotLike(String value) {
			addCriterion("share_user_id not like", value, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdIn(List<String> values) {
			addCriterion("share_user_id in", values, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdNotIn(List<String> values) {
			addCriterion("share_user_id not in", values, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdBetween(String value1, String value2) {
			addCriterion("share_user_id between", value1, value2, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andShareUserIdNotBetween(String value1, String value2) {
			addCriterion("share_user_id not between", value1, value2, "shareUserId");
			return (Criteria) this;
		}

		public Criteria andRelationChainIsNull() {
			addCriterion("relation_chain is null");
			return (Criteria) this;
		}

		public Criteria andRelationChainIsNotNull() {
			addCriterion("relation_chain is not null");
			return (Criteria) this;
		}

		public Criteria andRelationChainEqualTo(String value) {
			addCriterion("relation_chain =", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainNotEqualTo(String value) {
			addCriterion("relation_chain <>", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainGreaterThan(String value) {
			addCriterion("relation_chain >", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainGreaterThanOrEqualTo(String value) {
			addCriterion("relation_chain >=", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainLessThan(String value) {
			addCriterion("relation_chain <", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainLessThanOrEqualTo(String value) {
			addCriterion("relation_chain <=", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainLike(String value) {
			addCriterion("relation_chain like", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainNotLike(String value) {
			addCriterion("relation_chain not like", value, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainIn(List<String> values) {
			addCriterion("relation_chain in", values, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainNotIn(List<String> values) {
			addCriterion("relation_chain not in", values, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainBetween(String value1, String value2) {
			addCriterion("relation_chain between", value1, value2, "relationChain");
			return (Criteria) this;
		}

		public Criteria andRelationChainNotBetween(String value1, String value2) {
			addCriterion("relation_chain not between", value1, value2, "relationChain");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_relation
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_relation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}