package com.example.demo.entity;

public class UserRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_relation.user_relation_id
	 * @mbg.generated
	 */
	private String userRelationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_relation.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_relation.share_user_id
	 * @mbg.generated
	 */
	private String shareUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_relation.relation_chain
	 * @mbg.generated
	 */
	private String relationChain;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_relation.user_relation_id
	 * @return  the value of user_relation.user_relation_id
	 * @mbg.generated
	 */
	public String getUserRelationId() {
		return userRelationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_relation.user_relation_id
	 * @param userRelationId  the value for user_relation.user_relation_id
	 * @mbg.generated
	 */
	public void setUserRelationId(String userRelationId) {
		this.userRelationId = userRelationId == null ? null : userRelationId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_relation.user_id
	 * @return  the value of user_relation.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_relation.user_id
	 * @param userId  the value for user_relation.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_relation.share_user_id
	 * @return  the value of user_relation.share_user_id
	 * @mbg.generated
	 */
	public String getShareUserId() {
		return shareUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_relation.share_user_id
	 * @param shareUserId  the value for user_relation.share_user_id
	 * @mbg.generated
	 */
	public void setShareUserId(String shareUserId) {
		this.shareUserId = shareUserId == null ? null : shareUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_relation.relation_chain
	 * @return  the value of user_relation.relation_chain
	 * @mbg.generated
	 */
	public String getRelationChain() {
		return relationChain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_relation.relation_chain
	 * @param relationChain  the value for user_relation.relation_chain
	 * @mbg.generated
	 */
	public void setRelationChain(String relationChain) {
		this.relationChain = relationChain == null ? null : relationChain.trim();
	}
}