package com.example.demo.entity;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_name
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_no
	 * @mbg.generated
	 */
	private String userNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.photo
	 * @mbg.generated
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.level
	 * @mbg.generated
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.alipay_account
	 * @mbg.generated
	 */
	private String alipayAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.opend_id
	 * @mbg.generated
	 */
	private String opendId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_id
	 * @return  the value of user_info.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_id
	 * @param userId  the value for user_info.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_name
	 * @return  the value of user_info.user_name
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_name
	 * @param userName  the value for user_info.user_name
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_no
	 * @return  the value of user_info.user_no
	 * @mbg.generated
	 */
	public String getUserNo() {
		return userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_no
	 * @param userNo  the value for user_info.user_no
	 * @mbg.generated
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo == null ? null : userNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.photo
	 * @return  the value of user_info.photo
	 * @mbg.generated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.photo
	 * @param photo  the value for user_info.photo
	 * @mbg.generated
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.phone
	 * @return  the value of user_info.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.phone
	 * @param phone  the value for user_info.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.password
	 * @return  the value of user_info.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.password
	 * @param password  the value for user_info.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.level
	 * @return  the value of user_info.level
	 * @mbg.generated
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.level
	 * @param level  the value for user_info.level
	 * @mbg.generated
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.create_time
	 * @return  the value of user_info.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.create_time
	 * @param createTime  the value for user_info.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.alipay_account
	 * @return  the value of user_info.alipay_account
	 * @mbg.generated
	 */
	public String getAlipayAccount() {
		return alipayAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.alipay_account
	 * @param alipayAccount  the value for user_info.alipay_account
	 * @mbg.generated
	 */
	public void setAlipayAccount(String alipayAccount) {
		this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.opend_id
	 * @return  the value of user_info.opend_id
	 * @mbg.generated
	 */
	public String getOpendId() {
		return opendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.opend_id
	 * @param opendId  the value for user_info.opend_id
	 * @mbg.generated
	 */
	public void setOpendId(String opendId) {
		this.opendId = opendId == null ? null : opendId.trim();
	}
}