package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WalletChangeRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public WalletChangeRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(String value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(String value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(String value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(String value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(String value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLike(String value) {
			addCriterion("record_id like", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotLike(String value) {
			addCriterion("record_id not like", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<String> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<String> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(String value1, String value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(String value1, String value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andLeftRmbIsNull() {
			addCriterion("left_rmb is null");
			return (Criteria) this;
		}

		public Criteria andLeftRmbIsNotNull() {
			addCriterion("left_rmb is not null");
			return (Criteria) this;
		}

		public Criteria andLeftRmbEqualTo(BigDecimal value) {
			addCriterion("left_rmb =", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbNotEqualTo(BigDecimal value) {
			addCriterion("left_rmb <>", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbGreaterThan(BigDecimal value) {
			addCriterion("left_rmb >", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("left_rmb >=", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbLessThan(BigDecimal value) {
			addCriterion("left_rmb <", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbLessThanOrEqualTo(BigDecimal value) {
			addCriterion("left_rmb <=", value, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbIn(List<BigDecimal> values) {
			addCriterion("left_rmb in", values, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbNotIn(List<BigDecimal> values) {
			addCriterion("left_rmb not in", values, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("left_rmb between", value1, value2, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andLeftRmbNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("left_rmb not between", value1, value2, "leftRmb");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andChangeRmbIsNull() {
			addCriterion("change_rmb is null");
			return (Criteria) this;
		}

		public Criteria andChangeRmbIsNotNull() {
			addCriterion("change_rmb is not null");
			return (Criteria) this;
		}

		public Criteria andChangeRmbEqualTo(BigDecimal value) {
			addCriterion("change_rmb =", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbNotEqualTo(BigDecimal value) {
			addCriterion("change_rmb <>", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbGreaterThan(BigDecimal value) {
			addCriterion("change_rmb >", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("change_rmb >=", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbLessThan(BigDecimal value) {
			addCriterion("change_rmb <", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbLessThanOrEqualTo(BigDecimal value) {
			addCriterion("change_rmb <=", value, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbIn(List<BigDecimal> values) {
			addCriterion("change_rmb in", values, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbNotIn(List<BigDecimal> values) {
			addCriterion("change_rmb not in", values, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("change_rmb between", value1, value2, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andChangeRmbNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("change_rmb not between", value1, value2, "changeRmb");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIsNull() {
			addCriterion("record_type is null");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIsNotNull() {
			addCriterion("record_type is not null");
			return (Criteria) this;
		}

		public Criteria andRecordTypeEqualTo(Integer value) {
			addCriterion("record_type =", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotEqualTo(Integer value) {
			addCriterion("record_type <>", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeGreaterThan(Integer value) {
			addCriterion("record_type >", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("record_type >=", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLessThan(Integer value) {
			addCriterion("record_type <", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLessThanOrEqualTo(Integer value) {
			addCriterion("record_type <=", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIn(List<Integer> values) {
			addCriterion("record_type in", values, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotIn(List<Integer> values) {
			addCriterion("record_type not in", values, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeBetween(Integer value1, Integer value2) {
			addCriterion("record_type between", value1, value2, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("record_type not between", value1, value2, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordStateIsNull() {
			addCriterion("record_state is null");
			return (Criteria) this;
		}

		public Criteria andRecordStateIsNotNull() {
			addCriterion("record_state is not null");
			return (Criteria) this;
		}

		public Criteria andRecordStateEqualTo(Integer value) {
			addCriterion("record_state =", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateNotEqualTo(Integer value) {
			addCriterion("record_state <>", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateGreaterThan(Integer value) {
			addCriterion("record_state >", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("record_state >=", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateLessThan(Integer value) {
			addCriterion("record_state <", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateLessThanOrEqualTo(Integer value) {
			addCriterion("record_state <=", value, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateIn(List<Integer> values) {
			addCriterion("record_state in", values, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateNotIn(List<Integer> values) {
			addCriterion("record_state not in", values, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateBetween(Integer value1, Integer value2) {
			addCriterion("record_state between", value1, value2, "recordState");
			return (Criteria) this;
		}

		public Criteria andRecordStateNotBetween(Integer value1, Integer value2) {
			addCriterion("record_state not between", value1, value2, "recordState");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wallet_change_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}