package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Wallet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet.waller_id
	 * @mbg.generated
	 */
	private String wallerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet.rmb
	 * @mbg.generated
	 */
	private BigDecimal rmb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet.balance
	 * @mbg.generated
	 */
	private BigDecimal balance;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet.waller_id
	 * @return  the value of wallet.waller_id
	 * @mbg.generated
	 */
	public String getWallerId() {
		return wallerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet.waller_id
	 * @param wallerId  the value for wallet.waller_id
	 * @mbg.generated
	 */
	public void setWallerId(String wallerId) {
		this.wallerId = wallerId == null ? null : wallerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet.user_id
	 * @return  the value of wallet.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet.user_id
	 * @param userId  the value for wallet.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet.rmb
	 * @return  the value of wallet.rmb
	 * @mbg.generated
	 */
	public BigDecimal getRmb() {
		return rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet.rmb
	 * @param rmb  the value for wallet.rmb
	 * @mbg.generated
	 */
	public void setRmb(BigDecimal rmb) {
		this.rmb = rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet.create_time
	 * @return  the value of wallet.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet.create_time
	 * @param createTime  the value for wallet.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet.balance
	 * @return  the value of wallet.balance
	 * @mbg.generated
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet.balance
	 * @param balance  the value for wallet.balance
	 * @mbg.generated
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}
}