package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WalletChangeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.record_id
	 * @mbg.generated
	 */
	private String recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.left_rmb
	 * @mbg.generated
	 */
	private BigDecimal leftRmb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.note
	 * @mbg.generated
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.change_rmb
	 * @mbg.generated
	 */
	private BigDecimal changeRmb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.record_type
	 * @mbg.generated
	 */
	private Integer recordType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_change_record.record_state
	 * @mbg.generated
	 */
	private Integer recordState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.record_id
	 * @return  the value of wallet_change_record.record_id
	 * @mbg.generated
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.record_id
	 * @param recordId  the value for wallet_change_record.record_id
	 * @mbg.generated
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId == null ? null : recordId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.user_id
	 * @return  the value of wallet_change_record.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.user_id
	 * @param userId  the value for wallet_change_record.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.left_rmb
	 * @return  the value of wallet_change_record.left_rmb
	 * @mbg.generated
	 */
	public BigDecimal getLeftRmb() {
		return leftRmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.left_rmb
	 * @param leftRmb  the value for wallet_change_record.left_rmb
	 * @mbg.generated
	 */
	public void setLeftRmb(BigDecimal leftRmb) {
		this.leftRmb = leftRmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.note
	 * @return  the value of wallet_change_record.note
	 * @mbg.generated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.note
	 * @param note  the value for wallet_change_record.note
	 * @mbg.generated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.create_time
	 * @return  the value of wallet_change_record.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.create_time
	 * @param createTime  the value for wallet_change_record.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.change_rmb
	 * @return  the value of wallet_change_record.change_rmb
	 * @mbg.generated
	 */
	public BigDecimal getChangeRmb() {
		return changeRmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.change_rmb
	 * @param changeRmb  the value for wallet_change_record.change_rmb
	 * @mbg.generated
	 */
	public void setChangeRmb(BigDecimal changeRmb) {
		this.changeRmb = changeRmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.record_type
	 * @return  the value of wallet_change_record.record_type
	 * @mbg.generated
	 */
	public Integer getRecordType() {
		return recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.record_type
	 * @param recordType  the value for wallet_change_record.record_type
	 * @mbg.generated
	 */
	public void setRecordType(Integer recordType) {
		this.recordType = recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_change_record.record_state
	 * @return  the value of wallet_change_record.record_state
	 * @mbg.generated
	 */
	public Integer getRecordState() {
		return recordState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_change_record.record_state
	 * @param recordState  the value for wallet_change_record.record_state
	 * @mbg.generated
	 */
	public void setRecordState(Integer recordState) {
		this.recordState = recordState;
	}
}