package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WithdrawalRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.record_id
	 * @mbg.generated
	 */
	private String recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.rmb
	 * @mbg.generated
	 */
	private BigDecimal rmb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.record_status
	 * @mbg.generated
	 */
	private Integer recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.record_type
	 * @mbg.generated
	 */
	private Integer recordType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column withdrawal_record.account
	 * @mbg.generated
	 */
	private String account;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.record_id
	 * @return  the value of withdrawal_record.record_id
	 * @mbg.generated
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.record_id
	 * @param recordId  the value for withdrawal_record.record_id
	 * @mbg.generated
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId == null ? null : recordId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.user_id
	 * @return  the value of withdrawal_record.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.user_id
	 * @param userId  the value for withdrawal_record.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.rmb
	 * @return  the value of withdrawal_record.rmb
	 * @mbg.generated
	 */
	public BigDecimal getRmb() {
		return rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.rmb
	 * @param rmb  the value for withdrawal_record.rmb
	 * @mbg.generated
	 */
	public void setRmb(BigDecimal rmb) {
		this.rmb = rmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.record_status
	 * @return  the value of withdrawal_record.record_status
	 * @mbg.generated
	 */
	public Integer getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.record_status
	 * @param recordStatus  the value for withdrawal_record.record_status
	 * @mbg.generated
	 */
	public void setRecordStatus(Integer recordStatus) {
		this.recordStatus = recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.create_time
	 * @return  the value of withdrawal_record.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.create_time
	 * @param createTime  the value for withdrawal_record.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.record_type
	 * @return  the value of withdrawal_record.record_type
	 * @mbg.generated
	 */
	public Integer getRecordType() {
		return recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.record_type
	 * @param recordType  the value for withdrawal_record.record_type
	 * @mbg.generated
	 */
	public void setRecordType(Integer recordType) {
		this.recordType = recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column withdrawal_record.account
	 * @return  the value of withdrawal_record.account
	 * @mbg.generated
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column withdrawal_record.account
	 * @param account  the value for withdrawal_record.account
	 * @mbg.generated
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}
}