package com.example.demo.dao;

import com.example.demo.entity.RechargeRecord;
import com.example.demo.entity.RechargeRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RechargeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	long countByExample(RechargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int deleteByExample(RechargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int insert(RechargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int insertSelective(RechargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	List<RechargeRecord> selectByExample(RechargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	RechargeRecord selectByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") RechargeRecord record,
			@Param("example") RechargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") RechargeRecord record, @Param("example") RechargeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RechargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recharge_record
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RechargeRecord record);

	List<Map<String, String>> getRechargeRecordList(Map<String, String> param);

	Map<String, String> getRechargeRrcordTotal(Map<String, String> param);
}