package com.example.demo.dao;

import com.example.demo.entity.UserInfo;
import com.example.demo.entity.UserInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	long countByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int deleteByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	List<UserInfo> selectByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	UserInfo selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserInfo record);

	List<Map<String, String>> getAllUser();

	Map<String, String> getUserInfo(String userId);

	Map<String, String> getUserByPhone(String phone);

	int updatePassword(String phone, String pwd);

	int UpdateUserOpenId(String record_id, String open_id);
}