package com.example.demo.dao;

import com.example.demo.entity.WalletChangeRecord;
import com.example.demo.entity.WalletChangeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WalletChangeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	long countByExample(WalletChangeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int deleteByExample(WalletChangeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int insert(WalletChangeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int insertSelective(WalletChangeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	List<WalletChangeRecord> selectByExample(WalletChangeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	WalletChangeRecord selectByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") WalletChangeRecord record,
			@Param("example") WalletChangeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") WalletChangeRecord record,
			@Param("example") WalletChangeRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(WalletChangeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_change_record
	 * @mbg.generated
	 */
	int updateByPrimaryKey(WalletChangeRecord record);

	int insertRecordForRecharge(String record_id, String change_record_id);

	int insertRecordForUnfreeze(String user_id, String record_id);

	int insertRecordForIndirectRechargeReward(String record_id, String change_record_id);

	int insertRecordForDirectRechargeReward(String record_id, String change_record_id);

	int insertRecordForWithdrawal(String change_record_id, String record_id);
}